datos = read.csv("test.csv")
ExpDes <- c("Lattice")
BiplotFormat <- c("pdf")
plot3D <- c("TRUE")
polygoner <- c("TRUE")
analysis <- c("AMMI")
LSMeans_par <- c("NA,NA,NA")
traits <- c("YLD")
tmp <- c("5132")
selected <- c("Toluca,Obregon")
source("/home/galaxy/galaxy-new/tools/GEA-R/AMMI/AMMI&SREG.R")
AMMISREG()
