datos = read.csv("test.csv")
ExpDes <- c("Lattice")
BiplotFormat <- c("pdf")
plot3D <- c("TRUE")
polygoner <- c("TRUE")
analysis <- c("AMMI")
LSMeans_par <- c("NA,NA,NA")
traits <- c("YLD")
tmp <- c("25421")
selected <- c("Batan,Toluca,Obregon,AguaFria,Tlatizapan,Celaya,Tuxtla,Ameca")
source("/home/galaxy/galaxy-new/tools/GEA-R2/AMMI&SREG.R")
AMMISREG()
