datos = read.csv("input.csv")
file_nameCOV = read.csv("cov.csv")
ExpDes <- c("Lattice")
cpv <- c(0.2)
traits <- c("YLD")
typecov <- c("env")
tmp <- c("9025")
selected <- c("Batan,Toluca,Obregon,AguaFria,Tlatizapan,Celaya,Tuxtla,Ameca")
source("/home/dquoc/galaxy/tools/FRegression/FactorialRegression.R")
REGFACT()
