
datos = read.csv("Yield_Data_for_CovENV.csv")
file_nameCOV = read.csv("CovENV_Data.csv")
ExpDes <- c("Lattice")
traits <- c("YLD")
typecov <-c("env")
cpv <-c("0.2")
selected <- c("Batan,Toluca,Obregon,AguaFria,Tlatizapan,Celaya,Tuxtla,Ameca")
source("/home/dquoc/galaxy/tools/FRegression/FactorialRegression.R")
REGFACT()
